config/routes.rb
Tasklist::Application.routes.draw do
  resources :priorities

  resources :categories

  resources :users
  get 'signup', to: 'users#new'

  resources :tasks_categories

  resources :tasks
  
  resources :subtasks

  resources :main_tasks, controller: 'tasks', type: 'main_task'

  resources :sessions, only: [:new, :create]

  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  
  resources :tasks do
    post 'mark_done', on: :member
  end 

    post '/subtasks/new', to: 'subtasks#new'

  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :priority
  has_many :tasks_categories, dependent: :destroy
  has_many :categories, through: :tasks_categories

  validates :name, presence: true

  scope :finished, -> { where done:true }
  scope :unfinished, -> { where done:[nil, false] }

  def task_category(category)
    TasksCategory.where(category_id: category ).where(task_id: self.id ).first.id
  end

  def excluded_categories
     Category.all.select{ |c| !c.tasks.include? self }
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:show, :new, :edit, :create, :update]
  before_action :ensure_that_signed_in, except: [:show]
  before_action :set_priorities
  before_action :ensure_that_owner, only: [:edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @done_tasks = done_tasks
    @tasks = tasks

    order = params[:order] || 'date'
    
    case order
      when 'name' then @tasks.sort_by!{ |t| t.name }
      when 'date' then @tasks.sort_by!{ |t| t.date }
      when 'type' then @tasks.sort_by!{ |t| t.type }
      when 'priority' then @tasks = priority_tasks
    end    
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @tasks_category = TasksCategory.new
  end

  # GET /tasks/new
  def new
    @task = MainTask.new
  end

  # GET /tasks/1/edit
  def edit
    @maintasks = current_user.main_tasks
  end

  def mark_done
    task = Task.find(params[:id])
    task.update_attribute(:done, true)
    text = set_done_text(task)

    redirect_to :back, notice: text
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        current_user.tasks << @task

        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy if current_user == @task.user
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end
  
    def set_categories
      @categs = Category.all
    end

    def set_priorities
      @priorities = Priority.all.order(:value)
    end

    def set_done_text(task)
      if task.priority and task.priority.done_text and task.priority.done_text!=""
        text = task.priority.done_text
      else
        text = "task finished!"
      end
    end

    def ensure_that_owner
      if @task.user != current_user 
        redirect_to :back, notice: 'can not edit task if not task owner'
      end
    end 

    def ensure_that_signed_in
      if current_user.nil?
        redirect_to signin_path
      end
    end

    def done_tasks
      current_user.main_tasks.finished
    end

    def tasks
      current_user.main_tasks.unfinished
    end

    def priority_tasks
      current_user.main_tasks.unfinished.includes(:priority).order("priorities.value")
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:main_task).permit(:name, :date, :done, :type, :info, :main_task_id, :user_id, :priority_id)
    end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if @task.type == "Subtask" %>
    <div class="field">
      <%= f.label :main_task %>
      <%= f.select :main_task_id, options_from_collection_for_select(@maintasks, :id, :name, selected: @task.main_task_id) %>
    </div>   
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :done %>
  </div>
  <div class="field">    
    <%= f.hidden_field :type %>
  </div>
  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_area :info %>
  </div>

  <div class="field">
    <%= f.label :priority %>
    <%= f.select :priority_id, options_from_collection_for_select(@priorities, :id, :to_s, selected: @task.priority_id) %>
  </div> 


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_table_contents.html.erb
  <tbody>
    <% tasks.each do |task| %>
      <tr>
        <td><%= link_to task.name, task %></td>
        <td><%= task.date %></td>
        <td><%= link_to task.priority, task.priority if task.priority %></td>
        <% if task.type == "Subtask" %>  
          <td>  
            <% if task.main_task %>
              <%= task.main_task.name %>
            <% end %>
          </td>
        <% end %>
        <% if current_user == task.user %>
          <td><%= link_to 'Edit', edit_task_path(task) %></td>
          <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td>
            <% if !task.done %>
              <%= button_to 'Done!', mark_done_task_path(task.id), method: :post %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>

app/views/tasks/_table_head_index.html.erb
  <thead>
    <tr>
      <% if tasks.length > 0 and tasks.first.type == "Subtask" %>
        <th><%= link_to 'Name', subtasks_path(order:"name") %></th>
        <th><%= link_to 'Date', subtasks_path(order:"date") %></th>
        <th><%= link_to 'Priority', subtasks_path(order:'priority') %></th>
        <th>Main Task</th>
      <% else %>
        <th><%= link_to 'Name', tasks_path(order:"name") %></th>
        <th><%= link_to 'Date', tasks_path(order:"date") %></th>
        <th><%= link_to 'Priority', tasks_path(order:'priority') %></th>
      <% end %>
    </tr>
  </thead>

app/views/tasks/_table_head_show.html.erb
<thead>
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Priority</th>
  </tr>
</thead>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<% if @tasks.first and @tasks.first.type == "Subtask" %>
  <h1>Subtasks to do</h1>
<% else %>
  <h1>Tasks to do</h1>
<% end %>

<table>
  <%= render 'table_head_index', tasks: @tasks %>
  <%= render 'table_contents', tasks: @tasks %>
</table>

<p><%= link_to 'New Task', new_task_path %></p>

<h1> Finished tasks </h1>

<table>
  <%= render 'table_head_show' %>
  <%= render 'table_contents', tasks: @done_tasks %>
</table>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @task.name %> </h2>

<strong>Info:</strong>

<p class="infobox">
    <%= @task.info %>
</p>

<p>
  <strong>Date:</strong>
  <%= @task.date %>
</p>

<p>
  <strong>priority:</strong> 
  <%= link_to @task.priority, @task.priority if @task.priority %>
</p>

<p>
  Categories: 
  <ul>
    <% @task.categories.each do |category| %>
      <li><%= link_to category, category %> 
      <% if current_user == @task.user %>
        <%= link_to 'remove', tasks_category_path(@task.task_category(category.id)), method: :delete %></li>
      <% end %>
    <% end %>
  </ul>
</p>

<% if current_user == @task.user %>
<p> 
  <%= form_for(@tasks_category) do |f| %>
    Add category:
    <%= f.hidden_field :task_id, value: @task.id %>
    <%= f.select :category_id, options_from_collection_for_select(@task.excluded_categories, :id, :name) %>
    <%= f.submit value: "add" %>
  <% end %>
</p>

<% end %>

<p>
  <strong>Type:</strong>
  <%= @task.type %>
</p>


<% if @task.type == "Subtask" and @task.main_task %>
  Main task: <%= link_to @task.main_task.name, @task.main_task %>
<% end %>


<% if @task.type == "MainTask" %>
  <h3>Subtasks</h3> 

  <table>
    <%= render 'table_head_show' %>
    <%= render 'table_contents', tasks: @task.subtasks.unfinished %>
  </table>

  <% if current_user and current_user == @task.user %>
    <%= link_to 'add new subtask', new_subtask_path(@task.id), method: :post %> 
  <% end %>


  <h3>Finished subtasks</h3>

  <table>
    <%= render 'table_head_show' %>
    <%= render 'table_contents', tasks: @task.subtasks.finished %>
  </table>

<% end %>

<p>
  <% if !@task.done %>
    <% if current_user == @task.user %>
      <%= button_to 'Done!', mark_done_task_path(@task.id), method: :post %>
    <% end %>      
  <% else %>
    Task is done!
  <% end %>
</p>

<% if current_user == @task.user %>
  <%= link_to 'Edit', edit_task_path(@task) %> 
  <%= link_to 'Destroy', task_path(@task), method: :delete, data: { confirm: 'Are you sure?' } %>|
<% end %>
<%= link_to 'Back', tasks_path %>