config/routes.rb
Tasklist::Application.routes.draw do
  resources :priorities

  resources :categories

  resources :users
  get 'signup', to: 'users#new'

  resources :tasks_categories

  resources :tasks
  
  resources :subtasks

  resources :main_tasks, controller: 'tasks', type: 'main_task'

  resources :sessions, only: [:new, :create]

  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  
  resources :tasks do
    post 'mark_done', on: :member
  end 

    post '/subtasks/new', to: 'subtasks#new'

  root 'tasks#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  has_many :main_tasks, dependent: :destroy
  has_many :subtasks, dependent: :destroy

  has_secure_password

  validates :username, presence: true
  validates :username, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_correct_user, only: [:edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Password was successfully changed.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

    def ensure_that_correct_user
      if @user != current_user
        redirect_to :back, notice: 'can not destroy/update wrong user'
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% if @user.new_record? %>
      <%= f.label :username %><br>
      <%= f.text_field :username %>
    <% end %>
  </div>
  <div class="field">
    <% if @user.new_record? %>
      <%= f.label :password %><br />
    <% else %>
      <%= f.label :password, 'new password' %><br />
    <% end %>    
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <% if @user.new_record? %>
      <%= f.label :password_confirmation %><br />
    <% else %>
      <%= f.label :password_confirmation, 'new password confirmation' %><br />
    <% end %>    

    <%= f.password_field :password_confirmation  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password of <%= @user.username %></h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<ul>
 <% @users.each do |user| %>
  <li>
    <%= link_to user.username, user %></td>        
  </li>
 <% end %>
</ul>

<br>

<%= link_to 'Create account', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2>  <%= @user.username %> </h2>

<p>
  <h4>Tasks:</h4>
  <ul>
    <% @user.main_tasks.unfinished.each do |task| %>
      <li> <%= link_to task.name, task %> <%= task.date %> </li>
      <ul>
        <% task.subtasks.unfinished.each do |subtask| %>
          <li> <%= link_to subtask.name, subtask %> <%= subtask.date %> </li>
        <% end %>
      </ul>
    <% end %>
  </ul>
</p>

<% if @user == current_user %>
  <p>
    <%= link_to 'New task', new_task_path %>
    <%= link_to 'New category', new_category_path %>
    <%= link_to 'Change password', edit_user_path(@user) %>
    <%= link_to 'Delete account', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

<%= link_to 'Back', users_path %>