config/routes.rb
Tasklist::Application.routes.draw do
  resources :priorities

  resources :categories

  resources :users
  get 'signup', to: 'users#new'

  resources :tasks_categories

  resources :tasks
  
  resources :subtasks

  resources :main_tasks, controller: 'tasks', type: 'main_task'

  resources :sessions, only: [:new, :create]

  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  
  resources :tasks do
    post 'mark_done', on: :member
  end 

    post '/subtasks/new', to: 'subtasks#new'

  root 'tasks#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tasks_categories, dependent: :destroy
  has_many :tasks, through: :tasks_categories

  validates :name, presence: true

  def tasks_of_user(user)
     tasks.unfinished.order(:date).select{|t| t.user == user}
  end

  def to_s
    "#{name}"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private

    def ensure_that_signed_in
      if current_user.nil?
        redirect_to signin_path, notice: 'Sign in first'
      end
    end


    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category, category %></td>
        <% if current_user %>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user %>
  <%= link_to 'New Category', new_category_path %>
<% end %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
<p>
  Tasks in this category:
  <% if current_user %>
    <ul>
      <% @category.tasks_of_user(current_user).each do |task| %>
        <li> 
          <%= link_to task.name, task %> <%= task.date %>    
          <% if not task.main_task_id.nil? %>   
            main task: <%= link_to task.main_task.name, task_path(task.main_task) %>
          <% end %>
        </li>
      <% end %>
    </ul>

  <% end %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> 
<%= link_to 'Destroy', category_path(@category), method: :delete, data: { confirm: 'Are you sure?' } %>
|
<%= link_to 'Back', categories_path %>