config/routes.rb
Tasklist::Application.routes.draw do
  resources :priorities

  resources :categories

  resources :users
  get 'signup', to: 'users#new'

  resources :tasks_categories

  resources :tasks
  
  resources :subtasks

  resources :main_tasks, controller: 'tasks', type: 'main_task'

  resources :sessions, only: [:new, :create]

  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  
  resources :tasks do
    post 'mark_done', on: :member
  end 

    post '/subtasks/new', to: 'subtasks#new'

  root 'tasks#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasklist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="nav">
    <%= link_to 'Tasks', tasks_path %>
    <%= link_to 'Subtasks', subtasks_path %>
    <%= link_to 'Categories', categories_path %>
    <%= link_to 'Priorities', priorities_path %>
    <%= link_to 'Users', users_path %>
    || 
    <% if current_user %>
      <%= link_to 'Add new task', new_task_path %>
      <%= link_to 'Add new category', new_category_path %>
      <%= link_to 'Add new priority', new_priority_path %>
      ||    
      Signed in: <%= link_to current_user.username, current_user %>  
      <%= link_to 'Signout', signout_path, method: :delete %>
    <% else %>
      <%= link_to 'Signin', signin_path %>
      <%= link_to 'New user', signup_path %>  
    <% end %>    

  </div>

<%= yield %>

</body>
</html>